apiVersion: v1
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      app: servicebroker-openshift
    name: servicebroker-openshift
  spec:
    replicas: 1
    selector:
      app: servicebroker-openshift
      deploymentconfig: servicebroker-openshift
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: servicebroker-openshift
          deploymentconfig: servicebroker-openshift
      spec:
        containers:
        - env:
          - name: BROKERPORT
            value: "8888"
          - name: CASSANDRAIMAGE
            value: 172.25.163.133:5000/service-brokers/cassandra-openshift-orchestration-3
          - name: DATAFOUNDRYPROXYADDR
            value: volume.datafoundry.new.dataos.io
          - name: DNSMASQ_SERVER
            value: 192.168.12.8
          - name: ELASTICSEARCHVOLUMEIMAGE
            value: 172.25.163.133:5000/service-brokers/elasticsearch
          - name: ENDPOINTSUFFIX
            value: lo.dataos.io
          - name: ETCDBOOTIMAGE
            value: 172.25.163.133:5000/service-brokers/etcd-imported:v2.3.0
          - name: ETCDENDPOINT
            value: http://10.1.234.40:2379
          - name: ETCDIMAGE
            value: 172.25.163.133:5000/service-brokers/etcd-openshift-orchestration-2
          - name: ETCDPASSWORD
            value: rootpasswd
          - name: ETCDUSER
            value: root
          - name: ETCDVOLUMEIMAGE
            value: 172.25.163.133:5000/service-brokers/service-brokers-etcd-volumes
          - name: KAFKAIMAGE
            value: 172.25.163.133:5000/service-brokers/kafka-openshift-orchestration
          - name: KETTLEIMAGE
            value: 172.25.163.133:5000/service-brokers/kettle-service-2
          - name: MONGOVOLUMEIMAGE
            value: 172.25.163.133:5000/service-brokers/mongo-volumes
          - name: NIFIIMAGE
            value: 172.25.163.133:5000/service-brokers/nifi-imported
          - name: NODE_ADDRESSES
            value: 10.23.4.23,10.23.4.24,10.23.4.25,10.23.4.26,10.23.4.27
          - name: OPENSHIFTADDR
            value: 10.1.234.34:443
          - name: OPENSHIFTPASS
            value: "1234"
          - name: OPENSHIFTUSER
            value: hack
          - name: PYSPIDERIMAGE
            value: 172.25.163.133:5000/service-brokers/pyspider
          - name: RABBITMQIMAGE
            value: 172.25.163.133:5000/service-brokers/service-brokers-rabbitmq-volumes
          - name: REDISIMAGE
            value: registry.dataos.io/serviceborker/redis-openshift-2
          - name: REDISPHPADMINIMAGE
            value: 172.25.163.133:5000/service-brokers/php-redis-admin-imported
          - name: SBNAMESPACE
            value: service-brokers
          - name: SIMPLEFILEUPLOADERIMAGE
            value: 172.25.163.133:5000/service-brokers/simple-file-uploader
          - name: SPARKIMAGE
            value: 172.25.163.133:5000/service-brokers/spark-imported
          - name: STORMIMAGE
            value: 172.25.163.133:5000/service-brokers/storm-openshift-orchestration:v10_dep_dns
          - name: TENSORFLOWIMAGE
            value: 172.25.163.133:5000/service-brokers/tensorflow-imported:0.8.0123123
          - name: ZEPPLINIMAGE
            value: registry.new.dataos.io/zeppelin/zeppelin:0.7.3
          - name: ZOOKEEPEREXHIBITORIMAGE
            value: 172.25.163.133:5000/service-brokers/zookeeper--envxhibitor-imported-2
          - name: ZOOKEEPERIMAGE
            value: 172.25.163.133:5000/service-brokers/zookeeper-openshift-orchestration
          - name: REDISCLUSTERIMAGE
            value: registry.dataos.io/wangydtest/redis-sharding-node
          - name: REDISCLUSTERTRIBIMAGE
            value: registry.new.dataos.io/service-brokers/redis-cluster-master:v3
          - name: KAFKAVOLUMEIMAGE
            value: 172.25.163.133:5000/service-brokers/service-brokers-kafka-volumes
          - name: NEO4JVOLUMEIMAGE
            value: 172.25.163.133:5000/service-brokers/neo4j
          - name: REDIS32IMAGE
            value: registry.dataos.io/openshift/redis:3.2
          - name: NODE_DOMAINS
            value: node154.local.dataos.io,node155.local.dataos.io
          - name: STORMEXTERNALIMAGE
            value: registry.dataos.io/openshift/storm:external
          - name: EXTERNALZOOKEEPERSERVERS
            value: 10.1.236.92,10.1.236.93,10.1.236.94
          - name: OCSP_OCM
            value: temp
          - name: OCSP_OCM_PORT
            value: temp
          - name: OCSP_HDP_VERSION
            value: temp
          - name: OCSPIMAGE
            value: temp
          - name: DATAIKUIMAGE
            value: registry.new.dataos.io/dataiku/dataiku:latest
          - name: ANACONDAIMAGE
            value: registry.new.dataos.io/lixw/base-notebook:v1
          - name: MARIADBIMAGE
            value: registry.new.dataos.io/service-brokers/mariadb:10.2.12
          - name: PROMETHEUSMYSQLEXPORTERIMAGE
            value: registry.new.dataos.io/service-brokers/prometheus-mysqld_exporter:v0.10.0
          - name: PHPMYADMINIMAGE
            value: registry.new.dataos.io/service-brokers/phpmyadmin:4.6
          - name: STORAGECLASSNAME
            value: gluster-heketi
          image: docker-registry.default.svc:5000/service-brokers/servicebroker-openshift:latest
          imagePullPolicy: Always
          name: servicebroker-openshift
          ports:
          - containerPort: 8888
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
kind: List
metadata: {}